[workspace]
default-members = ["section_02_control_onwership/ch_03_loop_condition"]
members = [
  "section_01_basics/ch_01_hello_world",
  "section_01_basics/ch_02_types_variables",
  "section_01_basics/ch_03_functions",
  "section_01_basics/ch_04_modules",
  "section_01_basics/exercise_module",
  "section_02_control_onwership/ch_01_ifelse_condition",
  "section_02_control_onwership/ch_02_match_condition",
  "section_02_control_onwership/ch_03_loop_condition",
]
resolver = "2"
